### ISSUE TITLE
[自荐] 网易云音乐 for VS Code

### ISSUE THREAD

**Issue by nondanee** [formulahendry/awesome-vscode-cn#2]
https://github.com/nondanee/vsc-netease-music

**Comment by LuYue94** [comment]
> https://github.com/nondanee/vsc-netease-music

你可真是个人才

**Comment by formulahendry** [comment]
This extension does not have enough downloads to make sure its popularity. Keep this open for future feedback on this.

**Comment by TheEd0315** [comment]
> https://github.com/nondanee/vsc-netease-music

这个厉害，打算试试。

**Comment by formulahendry** [comment]
@nondanee 用了下，真香~

**Comment by formulahendry** [comment]
已添加至 https://github.com/formulahendry/awesome-vscode-cn#%E5%9B%BD%E4%BA%BA%E5%BC%80%E5%8F%91%E7%9A%84%E4%BC%98%E7%A7%80%E6%8F%92%E4%BB%B6

**Comment by nondanee** [comment]
Thx!
