### ISSUE TITLE
[自荐] Onedark Pro 

### ISSUE THREAD

**Issue by Binaryify** [formulahendry/awesome-vscode-cn#3]
https://github.com/Binaryify/OneDark-Pro/

**Comment by formulahendry** [comment]
@Binaryify Great! Would you mind sending PR directly? 😄

**Comment by Binaryify** [comment]
https://github.com/formulahendry/awesome-vscode-cn/pull/4

**Comment by formulahendry** [comment]
Added now. Thanks @Binaryify for the PR~
